language: ruby
rvm:
  - 2.3.0
#before_script:
#  - psql -c "CREATE USER gregory WITH PASSWORD '123';" -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - psql -c 'create database myapp_test' -U postgres

